{{- range .Values.schedules }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "velero.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
    {{- if $.Values.scheduleLabels }}
      {{- toYaml $.Values.scheduleLabels | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .schedule | quote }}
{{- with .template }}
  template:
    {{- toYaml . | nindent 4 }}
{{- end }}
---
{{- end }}
